name: Build Library

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      wd: ./lib
      bump: ./tools/dotnet-bump

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.300'
    - run: dotnet build
      working-directory: ${{env.wd}}
    - run: dotnet pack
      working-directory: ${{env.wd}}

# build dotnet-bump tool
    - run: dotnet build
      working-directory: ${{env.bump}}
    - run: dotnet pack
      working-directory: ${{env.bump}}
    - run: dotnet tool install dotnet-bump-version --configfile .config/disable-nuget.config --add-source .\tools\dotnet-bump\bin\
      working-directory: ./
    - run: dotnet tool restore
      working-directory: ./
    
